### ISSUE TITLE
Automate updating

### ISSUE THREAD

**Issue by Graham42** [uniphil/venvgit2#14]
Should be able to automate some of the upgrading by having a build that runs whenever there is a new version of pygit2 / libgit2. I will hopefully get to this in a couple months. Putting this here to remind myself.

**Comment by uniphil** [comment]
If nothing else, auto-pushing to pypi from travis on successful tagged builds would take a lot of steps out of keeping this up to date. I think I forgot to push last time.

**Comment by uniphil** [comment]
... aaaaand done. creating releases via github now triggers a deploy action.
