### ISSUE TITLE
maint/v0.21

### ISSUE THREAD

**Issue by ashleyblackmore** [uniphil/venvgit2#7]
Hey, there is a patch I would like to use, that exists on the libgit2 maint/v0.21 branch. How can I use that with venvgit2?

Cheers!

**Comment by Graham42** [comment]
1. Make sure you have your virtualenv activated where you want venvgit2 installed. 
1. Clone this repo and `cd` into the folder
1. `git submodule init && git submodule update` 
1. `cd libgit2/ && git checkout origin/maint/v0.21 && cd ..`
1. `python setup.py install`

Hopefully that will work

**Comment by uniphil** [comment]
Yeah that should do it, I think. If you feel like committing with the libgit2 submodule poiting to the `maint` branch you need, I have no problem accepting a PR for that and pushing a release for it to pypi.

**Comment by ashleyblackmore** [comment]
Thanks so much @Graham42, @uniphil, appreciate it. That worked just fine. PR coming

**Comment by ashleyblackmore** [comment]
https://github.com/uniphil/venvgit2/pull/8

**Comment by uniphil** [comment]
Great! Glad it worked for you!
