### ISSUE TITLE
The latest version on pypi uses an 'invalid version'

### ISSUE THREAD

**Issue by dbaxa** [uniphil/venvgit2#9]
If you run `pip install venvgit2==0.21.libgitmaint.0` with pip 6.0.6 the following error is produced:

```
Collecting venvgit2==0.21.libgitmaint.0
  Using cached venvgit2-0.21.libgitmaint.0.tar.gz
    /home/dblack/myenv/lib/python3.4/site-packages/setuptools/dist.py:293: UserWarning: The version specified ('0.21.libgitmaint.0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
Collecting cffi>=0.8.6 (from venvgit2==0.21.libgitmaint.0)
  Using cached cffi-0.8.6.tar.gz
```

**Comment by uniphil** [comment]
The warning is accurate -- don't install that maintenance release unless you need it for the fix on the 0.21 maintenance branch of libgit2. I haven't read pep 440 yet, but I'll check it out.

It's just a warning, right? venvgit2 still installed?

**Comment by uniphil** [comment]
A quick skim of [PEP 440](https://www.python.org/dev/peps/pep-0440) makes me think we should be using a [Local Version Identifier](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers).

I don't have more time to look into this today, but @dbaxa if you wanted to propose a version name for this release, it would be much appreciated! (It's a special release that has a bug fix one person needed, it's not a normal release that everyone should install)

**Comment by uniphil** [comment]
@dbaxa if you were looking for a release tracking the latest maintenance release of libgit2 (`v0.21.5`), I just pushed it. Should be `venvgit2==v0.21.7`.

ps. @ashleyblackmore I think this libgit2 release has the fixes you needed, so you may want to use venvgit2 v0.21.7 as well.

**Comment by ashleyblackmore** [comment]
Thanks I'll let you know once I've tested

**Comment by dbaxa** [comment]
Thank you.
